# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bg
from sqlite3 import *
from PyQt5.QtWidgets import QMessageBox



class Ui_SignUp(object):
    def setupUi(self, SignUp):
        SignUp.setObjectName("SignUp")
        SignUp.resize(596, 422)
        SignUp.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        SignUp.setAttribute(QtCore.Qt.WA_NoSystemBackground, True)
        SignUp.setAttribute(QtCore.Qt.WA_TranslucentBackground, True)

        self.widget = QtWidgets.QWidget(SignUp)
        self.widget.setGeometry(QtCore.QRect(0, 0, 590, 420))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
" background-color:rgba(85, 98, 112, 200);\n"
" color:rgba(255, 255, 255, 200);\n"
" border-radius:5px\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
" padding-left:5px;\n"
" padding-top:5px;\n"
" background-color:rgba(255, 107, 107, 255);\n"
" background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
" background-color:rgba(255, 107, 107, 255);\n"
"}\n"
"QPushButton#ButtonSignUp{\n"
" background-color:rgba(85, 98, 112, 200);\n"
" color:rgba(255, 255, 255, 200);\n"
" border-radius:5px\n"
"}\n"
"QPushButton#ButtonSignUp:pressed{\n"
" padding-left:5px;\n"
" padding-top:5px;\n"
" background-color:rgba(255, 107, 107, 255);\n"
" background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#ButtonSignUp:hover{\n"
" background-color:rgba(255, 107, 107, 255);\n"
"}\n"
""

)
        self.widget.setObjectName("widget")
        self.LabelSignUp = QtWidgets.QLabel(self.widget)
        self.LabelSignUp.setEnabled(True)
        self.LabelSignUp.setGeometry(QtCore.QRect(290, 40, 260, 330))
        self.LabelSignUp.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"border-radius:10px")
        self.LabelSignUp.setText("")
        self.LabelSignUp.setObjectName("LabelSignUp")
        self.LabelBg = QtWidgets.QLabel(self.widget)
        self.LabelBg.setGeometry(QtCore.QRect(40, 25, 270, 360))
        self.LabelBg.setStyleSheet("border-image: url(:/BackgroundSignUp/backgroundLogIn.png);\n"
"border-radius:10px;")
        self.LabelBg.setText("")
        self.LabelBg.setObjectName("LabelBg")
        self.LabelTitle = QtWidgets.QLabel(self.widget)
        self.LabelTitle.setGeometry(QtCore.QRect(330, 70, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.LabelTitle.setFont(font)
        self.LabelTitle.setStyleSheet("color: rgba(0, 0, 0, 200);")
        self.LabelTitle.setObjectName("LabelTitle")
        self.TextUserName = QtWidgets.QLineEdit(self.widget)
        self.TextUserName.setGeometry(QtCore.QRect(330, 130, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TextUserName.setFont(font)
        self.TextUserName.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 200);\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px\n"
"")
        self.TextUserName.setMaxLength(16)
        self.TextUserName.setObjectName("TextUserName")
        self.TextPass = QtWidgets.QLineEdit(self.widget)
        self.TextPass.setGeometry(QtCore.QRect(330, 180, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TextPass.setFont(font)
        self.TextPass.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 200);\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px\n"
"")
        self.TextPass.setMaxLength(32)
        self.TextPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.TextPass.setObjectName("TextPass")
        self.ButtonSignUp = QtWidgets.QPushButton(self.widget)
        self.ButtonSignUp.setGeometry(QtCore.QRect(330, 300, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonSignUp.setFont(font)
        self.ButtonSignUp.setObjectName("ButtonSignUp")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(60, 50, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255, 255, 255, 200);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(60, 70, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgba(255, 255, 255, 200);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(60, 120, 191, 41))
        self.label_7.setStyleSheet("color:rgba(255, 255, 255, 220);")
        self.label_7.setObjectName("label_7")
        self.ButtonExit = QtWidgets.QPushButton(self.widget)
        self.ButtonExit.setGeometry(QtCore.QRect(520, 50, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ButtonExit.setFont(font)
        self.ButtonExit.setStyleSheet("color:red;\n"
"QPushButton\n"
"{\n"
"   color:white;\n"
"}")
        self.ButtonExit.setObjectName("ButtonExit")
        self.TextConfirm = QtWidgets.QLineEdit(self.widget)
        self.TextConfirm.setGeometry(QtCore.QRect(330, 230, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TextConfirm.setFont(font)
        self.TextConfirm.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 200);\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px\n"
"")
        self.TextConfirm.setText("")
        self.TextConfirm.setMaxLength(32)
        self.TextConfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.TextConfirm.setObjectName("TextConfirm")

        self.retranslateUi(SignUp)
        QtCore.QMetaObject.connectSlotsByName(SignUp)

# Connect   
        self.ButtonExit.clicked.connect(lambda : self.close(SignUp))
        self.ButtonSignUp.clicked.connect(self.signUp)

    def signUp(self):
        connection = connect('acc.db')
        cur = connection.cursor()
        try :
            if(self.TextPass.text()==self.TextConfirm.text()):
                cur.execute("insert into Account values('{}','{}')".format(self.TextUserName.text(),self.TextPass.text()))
                connection.commit()
                mess = QMessageBox()
                mess.setIcon(QMessageBox.Information)
                mess.setWindowIcon(QtGui.QIcon('information.png'))
                mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
                mess.setWindowTitle("Congratulations")
                mess.setText(" Sign Up successful ")
                mess.exec_()
            else :
                mess = QMessageBox()
                mess.setIcon(QMessageBox.Critical)
                mess.setWindowIcon(QtGui.QIcon('cancel.png'))
                mess.setStyleSheet(
                        "QLabel{min-height:30 px; font-size: 24px;}")
                mess.setWindowIcon(QtGui.QIcon('cancel.png'))
                mess.setWindowTitle("Error")
                mess.setText(" Password incorrect ")
                mess.exec_()
        except Error as e:
            mess = QMessageBox()
            mess.setIcon(QMessageBox.Critical)
            mess.setWindowIcon(QtGui.QIcon('cancel.png'))
            mess.setStyleSheet(
                    "QLabel{min-height:30 px; font-size: 24px;}")
            mess.setWindowIcon(QtGui.QIcon('cancel.png'))
            mess.setWindowTitle("Error")
            mess.setText(str(e))
            mess.exec_()
        connection.close()
        pass

    def close(self,SignUp):
        SignUp.close()


    def retranslateUi(self, SignUp):
        _translate = QtCore.QCoreApplication.translate
        SignUp.setWindowTitle(_translate("SignUp", "Sign Up"))
        self.LabelTitle.setText(_translate("SignUp", "Sign Up"))
        self.TextUserName.setPlaceholderText(_translate("SignUp", "User Name"))
        self.TextPass.setPlaceholderText(_translate("SignUp", "Password"))
        self.ButtonSignUp.setText(_translate("SignUp", "Sign Up"))
        self.label_5.setText(_translate("SignUp", "Student "))
        self.label_6.setText(_translate("SignUp", "Management System"))
        self.label_7.setText(_translate("SignUp", "Hi,\n"
"Register a brand new account!"))
        self.ButtonExit.setText(_translate("SignUp", "X"))
        self.TextConfirm.setPlaceholderText(_translate("SignUp", "Confirm Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUp = QtWidgets.QWidget()
    ui = Ui_SignUp()
    ui.setupUi(SignUp)
    SignUp.show()
    sys.exit(app.exec_())
