# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import Background
from PyQt5.QtCore import *
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QWidget, QFileDialog
from sqlite3 import *
from itertools import chain, combinations
import copy

class Ui_Form(QWidget):
        def setupUi(self, Form):
                Form.setObjectName("Form")
                Form.resize(1143, 722)
                self.widget = QtWidgets.QWidget(Form)
                self.widget.setGeometry(QtCore.QRect(10, 20, 1121, 691))
                self.widget.setObjectName("widget")
                self.TitleLabel = QtWidgets.QLabel(self.widget)
                self.TitleLabel.setGeometry(QtCore.QRect(460, 60, 171, 111))
                font = QtGui.QFont()
                font.setPointSize(25)
                font.setBold(True)
                font.setWeight(75)
                self.TitleLabel.setFont(font)
                self.TitleLabel.setStyleSheet("color: rgba(255,255,255,210);")
                self.TitleLabel.setObjectName("TitleLabel")
                self.bg = QtWidgets.QLabel(self.widget)
                self.bg.setGeometry(QtCore.QRect(20, 20, 1081, 651))
                self.bg.setStyleSheet("\n"
        "border-image: url(:/bg/bg.jpg);\n"
        "border-radius: 20px;")
                self.bg.setText("")
                self.bg.setObjectName("bg")
                self.bg_2 = QtWidgets.QLabel(self.widget)
                self.bg_2.setGeometry(QtCore.QRect(20, 20, 1081, 651))
                self.bg_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(76, 76, 76, 255), stop:1 rgba(255, 255, 255, 255));\n"
        "border-radius: 20px;")
                self.bg_2.setText("")
                self.bg_2.setObjectName("bg_2")
                self.NewButton = QtWidgets.QPushButton(self.widget)
                self.NewButton.setGeometry(QtCore.QRect(890, 180, 141, 51))
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.NewButton.setFont(font)
                self.NewButton.setStyleSheet("QPushButton#NewButton{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
        "color: rgba(255,255,255,210);\n"
        "border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton#NewButton:hover{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
        "}\n"
        "\n"
        "QPushButton#NewButton:pressed{\n"
        "padding-left:5px;\n"
        "padding-top:5px;\n"
        "background-color:rgba(105,118,132,200);\n"
        "}")
                self.NewButton.setObjectName("NewButton")
                self.SaveButton = QtWidgets.QPushButton(self.widget)
                self.SaveButton.setGeometry(QtCore.QRect(890, 250, 141, 51))
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.SaveButton.setFont(font)
                self.SaveButton.setStyleSheet("QPushButton#SaveButton{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
        "color: rgba(255,255,255,210);\n"
        "border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton#SaveButton:hover{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
        "}\n"
        "\n"
        "QPushButton#SaveButton:pressed{\n"
        "padding-left:5px;\n"
        "padding-top:5px;\n"
        "background-color:rgba(105,118,132,200);\n"
        "}")
                self.SaveButton.setObjectName("SaveButton")
                self.DeleteButton = QtWidgets.QPushButton(self.widget)
                self.DeleteButton.setGeometry(QtCore.QRect(890, 320, 141, 51))
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.DeleteButton.setFont(font)
                self.DeleteButton.setStyleSheet("QPushButton#DeleteButton{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
        "color: rgba(255,255,255,210);\n"
        "border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton#DeleteButton:hover{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
        "}\n"
        "\n"
        "QPushButton#DeleteButton:pressed{\n"
        "padding-left:5px;\n"
        "padding-top:5px;\n"
        "background-color:rgba(105,118,132,200);\n"
        "}")
                self.DeleteButton.setObjectName("DeleteButton")
                self.ExecuteButton = QtWidgets.QPushButton(self.widget)
                self.ExecuteButton.setGeometry(QtCore.QRect(890, 450, 141, 51))
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.ExecuteButton.setFont(font)
                self.ExecuteButton.setStyleSheet("QPushButton#ExecuteButton{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
        "color: rgba(255,255,255,210);\n"
        "border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton#ExecuteButton:hover{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
        "}\n"
        "\n"
        "QPushButton#ExecuteButton:pressed{\n"
        "padding-left:5px;\n"
        "padding-top:5px;\n"
        "background-color:rgba(105,118,132,200);\n"
        "}")
                self.ExecuteButton.setObjectName("ExecuteButton")
                self.QuitButton = QtWidgets.QPushButton(self.widget)
                self.QuitButton.setGeometry(QtCore.QRect(890, 550, 141, 51))
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.QuitButton.setFont(font)
                self.QuitButton.setStyleSheet("QPushButton#QuitButton{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
        "color: rgba(255,255,255,210);\n"
        "border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton#QuitButton:hover{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
        "}\n"
        "\n"
        "QPushButton#QuitButton:pressed{\n"
        "padding-left:5px;\n"
        "padding-top:5px;\n"
        "background-color:rgba(105,118,132,200);\n"
        "}")
                self.QuitButton.setObjectName("QuitButton")
                self.tableWidget = QtWidgets.QTableWidget(self.widget)
                self.tableWidget.setGeometry(QtCore.QRect(70, 250, 161, 361))
                self.tableWidget.setObjectName("tableWidget")
                self.tableWidget.setColumnCount(0)
                self.tableWidget.setRowCount(0)
                self.EditTestcase = QtWidgets.QTextEdit(self.widget)
                self.EditTestcase.setGeometry(QtCore.QRect(260, 180, 591, 331))
                self.EditTestcase.setObjectName("EditTestcase")
                self.KeyLine = QtWidgets.QLineEdit(self.widget)
                self.KeyLine.setGeometry(QtCore.QRect(260, 540, 591, 71))
                self.KeyLine.setObjectName("KeyLine")
                self.ImportButton = QtWidgets.QPushButton(self.widget)
                self.ImportButton.setGeometry(QtCore.QRect(70, 180, 161, 51))
                font = QtGui.QFont()
                font.setPointSize(15)
                font.setBold(True)
                font.setWeight(75)
                self.ImportButton.setFont(font)
                self.ImportButton.setStyleSheet("QPushButton#ImportButton{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20,47,78,219), stop:1 rgba(85,98,112,226));\n"
        "color: rgba(255,255,255,210);\n"
        "border-radius:5px;\n"
        "}\n"
        "\n"
        "QPushButton#ImportButton:hover{\n"
        "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
        "}\n"
        "\n"
        "QPushButton#ImportButton:pressed{\n"
        "padding-left:5px;\n"
        "padding-top:5px;\n"
        "background-color:rgba(105,118,132,200);\n"
        "}")
                self.ImportButton.setObjectName("ImportButton")
                self.bg_2.raise_()
                self.bg.raise_()
                self.TitleLabel.raise_()
                self.NewButton.raise_()
                self.SaveButton.raise_()
                self.DeleteButton.raise_()
                self.ExecuteButton.raise_()
                self.QuitButton.raise_()
                self.tableWidget.raise_()
                self.EditTestcase.raise_()
                self.KeyLine.raise_()
                self.ImportButton.raise_()

                self.retranslateUi(Form)
                QtCore.QMetaObject.connectSlotsByName(Form)

                self.ImportButton.clicked.connect(self.browse_file)
                self.QuitButton.clicked.connect(self.close)
                self.ExecuteButton.clicked.connect(self.find_key)
                self.DeleteButton.clicked.connect(lambda: self.delete(self.tableWidget))
                self.loadData()

        def browse_file(self):
                fname = QFileDialog.getOpenFileName(self, "Open File", "", "All Files (*);;Text Documents (*.txt)")
                label = fname[0]
                if label != '':
                        connection = connect('testcase.db')
                        cur = connection.cursor()
                        query = f"""INSERT INTO FileName VALUES ('{label}')"""
                        cur.execute(query)
                        connection.commit()
                        self.loadData()
                        connection.close()
        
        def loadData(self):
                connection = connect('testcase.db')
                cur = connection.cursor()
                res = cur.execute("SELECT * FROM FileName")
                for row_number, row_data in enumerate(res):
                        self.tableWidget.setRowCount(row_number)
                        self.tableWidget.setColumnCount(len(row_data))
                        self.tableWidget.insertRow(row_number)
                        for column_number, data in enumerate(row_data):
                                self.tableWidget.setItem(
                                row_number, column_number, QtWidgets.QTableWidgetItem(str(self.strip_filename(data))))
                self.tableWidget.sortItems(0, QtCore.Qt.AscendingOrder)
                
                connection.close()
                
        def strip_filename(self,filename):
                lst = filename.split("/")
                s = lst[-1]
                return s

        def find_key(self):
                pass
        def delete(self, tableWidget):
                mess = QMessageBox()
                mess.setIcon(QMessageBox.Warning)
                mess.setWindowIcon(QtGui.QIcon('warning.png'))
                mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
                mess.setWindowTitle("Delete File")
                mess.setText("Are you sure you want to delete this file ?")
                mess.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
                question = mess.exec_()

                try:
                        if question == QMessageBox.Yes:
                                index = tableWidget.currentRow()
                                data = tableWidget.item(index, 0).text()
                                connection = connect('testcase.db')
                                cur = connection.cursor()
                                cur.execute("DELETE FROM FileName WHERE FileName LIKE '%{}'".format(data))
                                connection.commit()
                                tableWidget.removeRow(index)

                except Error as e:
                        mess = QMessageBox()
                        mess.setIcon(QMessageBox.Critical)
                        mess.setWindowIcon(QtGui.QIcon('cancel.png'))
                        mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
                        mess.setWindowIcon(QtGui.QIcon('cancel.png'))
                        mess.setWindowTitle("Error")
                        mess.setText(e)
                        mess.exec_()
                pass


        def close(self, Form):
                mess = QMessageBox()
                mess.setIcon(QMessageBox.Warning)
                mess.setWindowTitle("Window Close")
                mess.setWindowIcon(QtGui.QIcon('warning.png'))
                mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
                mess.setText("Are you sure you want to close the window ?")
                mess.setStandardButtons(QMessageBox.Yes | QMessageBox.No )
                question = mess.exec_()
                if question == QMessageBox.Yes :
                        Form.close()


        def retranslateUi(self, Form):
                _translate = QtCore.QCoreApplication.translate
                Form.setWindowTitle(_translate("Form", "Form"))
                self.TitleLabel.setText(_translate("Form", "FD Tool"))
                self.NewButton.setText(_translate("Form", "New"))
                self.SaveButton.setText(_translate("Form", "Save"))
                self.DeleteButton.setText(_translate("Form", "Delete"))
                self.ExecuteButton.setText(_translate("Form", "Execute"))
                self.QuitButton.setText(_translate("Form", "Quit"))
                self.ImportButton.setText(_translate("Form", "Open"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
