# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FindWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import BackGround
import sqlite3

class Ui_FindWindow(object):
    def setupUi(self, FindWindow):
        FindWindow.setObjectName("FindWindow")
        FindWindow.resize(833, 730)
        self.centralwidget = QtWidgets.QWidget(FindWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 821, 700))
        self.Background.setStyleSheet("background-image: url(:/Main/background.png);")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.titleFind = QtWidgets.QLabel(self.centralwidget)
        self.titleFind.setGeometry(QtCore.QRect(30, 10, 750, 100))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.titleFind.setFont(font)
        self.titleFind.setStyleSheet("color: rgb(255, 255, 255);")
        self.titleFind.setAlignment(QtCore.Qt.AlignCenter)
        self.titleFind.setObjectName("titleFind")
        self.TextStudentID = QtWidgets.QLineEdit(self.centralwidget)
        self.TextStudentID.setGeometry(QtCore.QRect(210, 130, 391, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.TextStudentID.setFont(font)
        self.TextStudentID.setText("")
        self.TextStudentID.setObjectName("TextStudentID")
        self.ButtonFind = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonFind.setGeometry(QtCore.QRect(630, 130, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonFind.setFont(font)
        self.ButtonFind.setObjectName("ButtonFind")
        self.ButtonQuit = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonQuit.setGeometry(QtCore.QRect(335, 600, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonQuit.setFont(font)
        self.ButtonQuit.setObjectName("ButtonQuit")
        self.LabelStudentID = QtWidgets.QLabel(self.centralwidget)
        self.LabelStudentID.setGeometry(QtCore.QRect(40, 130, 160, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LabelStudentID.setFont(font)
        self.LabelStudentID.setStyleSheet("color: rgb(255, 255, 255);")
        self.LabelStudentID.setObjectName("LabelStudentID")
        self.TableData = QtWidgets.QTableWidget(self.centralwidget)
        self.TableData.setGeometry(QtCore.QRect(50, 220, 721, 330))
        self.TableData.setObjectName("TableData")
        self.TableData.setColumnCount(4)
        self.TableData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableData.setHorizontalHeaderItem(0, item)
        self.TableData.setColumnWidth(0,100)
        item = QtWidgets.QTableWidgetItem()
        self.TableData.setHorizontalHeaderItem(1, item)
        self.TableData.setColumnWidth(1,250)
        item = QtWidgets.QTableWidgetItem()
        self.TableData.setHorizontalHeaderItem(2, item)
        self.TableData.setColumnWidth(2,250)
        item = QtWidgets.QTableWidgetItem()
        self.TableData.setHorizontalHeaderItem(3, item)
        self.TableData.setColumnWidth(3,100)
        FindWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FindWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 26))
        self.menubar.setObjectName("menubar")
        FindWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FindWindow)
        self.statusbar.setObjectName("statusbar")
        FindWindow.setStatusBar(self.statusbar)

# ? set title
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        FindWindow.setWindowIcon(icon)

        self.retranslateUi(FindWindow)
        QtCore.QMetaObject.connectSlotsByName(FindWindow)

        # ? Connect widget
        # Button quit
        self.ButtonQuit.clicked.connect(lambda:self.close(FindWindow))
        self.ButtonFind.clicked.connect(self.find)

# Quit
    def close(self,FindWindoW):
        mess = QMessageBox()
        mess.setIcon(QMessageBox.Warning)
        mess.setWindowTitle("Window Close")
        mess.setWindowIcon(QtGui.QIcon('warning.png'))
        mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
        mess.setText("Are you sure you want to close the windodw ?")
        mess.setStandardButtons(QMessageBox.Yes | QMessageBox.No )
        question = mess.exec_()
        if question == QMessageBox.Yes :
            FindWindoW.hide()

    def find(self):
        text =self.TextStudentID.text()
        connection = sqlite3.connect('StudentManagement.db')
        cur = connection.cursor()
        query = """SELECT * FROM STUDENT WHERE StudentID = '{}'""".format(text)
        res = cur.execute(query)

        data = cur.fetchall()

    # ? thêm mess
        if not data:
            mess = QMessageBox()
            mess.setIcon(QMessageBox.Critical)
            mess.setWindowIcon(QtGui.QIcon('cancel.png'))
            mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
            mess.setWindowTitle("Error")
            mess.setText(" Student is not exist ")
            mess.exec_()
            
        else:
            res = cur.execute(query)
            self.TableData.setRowCount(0)
            for row_number, row_data in enumerate(res):
                self.TableData.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.TableData.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

        



    def retranslateUi(self, FindWindow):
        _translate = QtCore.QCoreApplication.translate
        FindWindow.setWindowTitle(_translate("FindWindow", "Find"))
        self.titleFind.setText(_translate("FindWindow", "Student Information"))
        self.ButtonFind.setText(_translate("FindWindow", "Find"))
        self.ButtonQuit.setText(_translate("FindWindow", "Quit"))
        self.LabelStudentID.setText(_translate("FindWindow", "Student ID"))
        item = self.TableData.horizontalHeaderItem(0)
        item.setText(_translate("FindWindow", "StudentID"))
        item = self.TableData.horizontalHeaderItem(1)
        item.setText(_translate("FindWindow", "StudentName"))
        item = self.TableData.horizontalHeaderItem(2)
        item.setText(_translate("FindWindow", "StudentAddress"))
        item = self.TableData.horizontalHeaderItem(3)
        item.setText(_translate("FindWindow", "ClassID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindWindow = QtWidgets.QMainWindow()
    ui = Ui_FindWindow()
    ui.setupUi(FindWindow)
    FindWindow.show()
    sys.exit(app.exec_())


# INSERT INTO "Student" VALUES('T01','Bui Quoc Hao','kakaka','C01');