# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InsertWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import BackGround
import sqlite3
from PyQt5.QtWidgets import *
from PyQt5 import QtGui

class Ui_InsertWindow(object):
    def setupUi(self, InsertWindow):
        InsertWindow.setObjectName("InsertWindow")
        InsertWindow.setEnabled(True)
        InsertWindow.resize(710, 620)
        self.centralwidget = QtWidgets.QWidget(InsertWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InsertBackground = QtWidgets.QLabel(self.centralwidget)
        self.InsertBackground.setGeometry(QtCore.QRect(0, 0, 700, 580))
        self.InsertBackground.setStyleSheet("background-image: url(:/Main/background.png);")
        self.InsertBackground.setText("")
        self.InsertBackground.setObjectName("InsertBackground")
        self.ClassId = QtWidgets.QLabel(self.centralwidget)
        self.ClassId.setGeometry(QtCore.QRect(60, 390, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ClassId.setFont(font)
        self.ClassId.setStyleSheet("color: rgb(255, 255, 255);")
        self.ClassId.setObjectName("ClassId")
        self.ID = QtWidgets.QLabel(self.centralwidget)
        self.ID.setGeometry(QtCore.QRect(60, 150, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ID.setFont(font)
        self.ID.setStyleSheet("color: rgb(255, 255, 255);")
        self.ID.setObjectName("ID")
        self.Address = QtWidgets.QLabel(self.centralwidget)
        self.Address.setGeometry(QtCore.QRect(60,310, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Address.setFont(font)
        self.Address.setStyleSheet("color: rgb(255, 255, 255);")
        self.Address.setObjectName("Address")
        self.InsertTitel = QtWidgets.QLabel(self.centralwidget)
        self.InsertTitel.setGeometry(QtCore.QRect(60, 20, 570, 80))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.InsertTitel.setFont(font)
        self.InsertTitel.setStyleSheet("color: rgb(255, 255, 255);")
        self.InsertTitel.setAlignment(QtCore.Qt.AlignCenter)
        self.InsertTitel.setObjectName("InsertTitel")
        self.Name = QtWidgets.QLabel(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(60, 230, 250, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Name.setFont(font)
        self.Name.setStyleSheet("color: rgb(255, 255, 255);")
        self.Name.setObjectName("Name")
        self.IDText = QtWidgets.QLineEdit(self.centralwidget)
        self.IDText.setGeometry(QtCore.QRect(300, 150, 350, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.IDText.setFont(font)
        self.IDText.setText("")
        self.IDText.setObjectName("IDText")
        self.NameText = QtWidgets.QLineEdit(self.centralwidget)
        self.NameText.setGeometry(QtCore.QRect(300, 230, 350, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.NameText.setFont(font)
        self.NameText.setObjectName("NameText")
        self.AddressText = QtWidgets.QLineEdit(self.centralwidget)
        self.AddressText.setGeometry(QtCore.QRect(300, 310, 350, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.AddressText.setFont(font)
        self.AddressText.setObjectName("AddressText")
        self.ClassIDText = QtWidgets.QLineEdit(self.centralwidget)
        self.ClassIDText.setGeometry(QtCore.QRect(300, 390, 350, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.ClassIDText.setFont(font)
        self.ClassIDText.setObjectName("ClassIDText")
        self.ButtonInsert = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonInsert.setGeometry(QtCore.QRect(130, 490, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonInsert.setFont(font)
        self.ButtonInsert.setObjectName("ButtonInsert")
        self.ButtonQuit = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonQuit.setGeometry(QtCore.QRect(400, 490, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonQuit.setFont(font)
        self.ButtonQuit.setObjectName("ButtonQuit")
        InsertWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InsertWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 26))
        self.menubar.setObjectName("menubar")
        InsertWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InsertWindow)
        self.statusbar.setObjectName("statusbar")
        InsertWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InsertWindow)
        QtCore.QMetaObject.connectSlotsByName(InsertWindow)

        self.ButtonQuit.clicked.connect(lambda:self.close(InsertWindow))
        self.ButtonInsert.clicked.connect(self.insert)

    # ? set title
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        InsertWindow.setWindowIcon(icon)


    def close(self,InsertWindow):
        mess = QMessageBox()
        mess.setIcon(QMessageBox.Warning)
        mess.setWindowIcon(QtGui.QIcon('warning.png'))
        mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
        mess.setWindowTitle("Window Close")
        mess.setText(" Are you sure you want to close the windodw ? ")
        mess.setStandardButtons(QMessageBox.Yes | QMessageBox.No )
        question = mess.exec_()
        if question == QMessageBox.Yes :
            InsertWindow.hide()

    def insert(self):
        try:
            connection = sqlite3.connect('StudentManagement.db')
            cur = connection.cursor()
            query = f"""INSERT INTO Student VALUES('{self.IDText.text()}','{self.NameText.text()}','{self.AddressText.text()}','{self.ClassIDText.text()}')"""
            cur.execute(query)
            connection.commit()
            mess = QMessageBox()
            mess.setIcon(QMessageBox.Information)
            mess.setWindowIcon(QtGui.QIcon('information.png'))
            mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
            mess.setWindowTitle("Congratulations")
            mess.setText(" Insert Successful ")   
            mess.exec_()
        except:
            mess = QMessageBox()
            mess.setIcon(QMessageBox.Critical)
            mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
            mess.setWindowIcon(QtGui.QIcon('cancel.png'))
            mess.setWindowTitle("Error")
            mess.setText(" Error ")
            mess.exec_()
        



    def retranslateUi(self, InsertWindow):
        _translate = QtCore.QCoreApplication.translate
        InsertWindow.setWindowTitle(_translate("InsertWindow", "Insert"))
        self.InsertBackground.setWhatsThis(_translate("InsertWindow", "<html><head/><body><p><img src=\":/Main/background.png\"/></p></body></html>"))
        self.ClassId.setText(_translate("InsertWindow", "Class ID"))
        self.ID.setText(_translate("InsertWindow", "Student ID"))
        self.Address.setText(_translate("InsertWindow", "Student Address"))
        self.InsertTitel.setText(_translate("InsertWindow", "Insert Student"))
        self.Name.setText(_translate("InsertWindow", "Student Name"))
        self.ButtonInsert.setText(_translate("InsertWindow", "Insert"))
        self.ButtonQuit.setText(_translate("InsertWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InsertWindow = QtWidgets.QMainWindow()
    ui = Ui_InsertWindow()
    ui.setupUi(InsertWindow)
    InsertWindow.show()
    sys.exit(app.exec_())
