

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
import BackGround
from sqlite3 import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 1100, 811))
        self.Background.setStyleSheet("background-color: rgb(249, 243, 223);")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.Table_data = QtWidgets.QTableWidget(self.centralwidget)
        self.Table_data.setGeometry(QtCore.QRect(150, 170, 810, 400))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.Table_data.setFont(font)
        self.Table_data.setObjectName("Table_data")
        self.Table_data.setColumnCount(0)
        self.Table_data.setRowCount(0)
        self.labelInsert = QtWidgets.QLabel(self.centralwidget)
        self.labelInsert.setGeometry(QtCore.QRect(80, 640, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelInsert.setFont(font)
        # self.labelInsert.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelInsert.setObjectName("labelInsert")
        self.labelUpdate = QtWidgets.QLabel(self.centralwidget)
        self.labelUpdate.setGeometry(QtCore.QRect(80, 710, 130, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelUpdate.setFont(font)
        # self.labelUpdate.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelUpdate.setObjectName("labelUpdate")
        self.textID_insert = QtWidgets.QLineEdit(self.centralwidget)
        self.textID_insert.setGeometry(QtCore.QRect(230, 640, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.textID_insert.setFont(font)
        self.textID_insert.setObjectName("textID_insert")
        self.textName_insert = QtWidgets.QLineEdit(self.centralwidget)
        self.textName_insert.setGeometry(QtCore.QRect(430, 640, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.textName_insert.setFont(font)
        self.textName_insert.setObjectName("textName_insert")
        self.textPrice_insert = QtWidgets.QLineEdit(self.centralwidget)
        self.textPrice_insert.setGeometry(QtCore.QRect(630, 640, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.textPrice_insert.setFont(font)
        self.textPrice_insert.setObjectName("textPrice_insert")
        self.textId_update = QtWidgets.QLineEdit(self.centralwidget)
        self.textId_update.setGeometry(QtCore.QRect(230, 710, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.textId_update.setFont(font)
        self.textId_update.setObjectName("textId_update")
        self.textName_update = QtWidgets.QLineEdit(self.centralwidget)
        self.textName_update.setGeometry(QtCore.QRect(430, 710, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.textName_update.setFont(font)
        self.textName_update.setObjectName("textName_update")
        self.textPrice_update = QtWidgets.QLineEdit(self.centralwidget)
        self.textPrice_update.setGeometry(QtCore.QRect(630, 710, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.textPrice_update.setFont(font)
        self.textPrice_update.setObjectName("textPrice_update")
        self.Titel = QtWidgets.QLabel(self.centralwidget)
        self.Titel.setGeometry(QtCore.QRect(0, 40, 1100, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Titel.setFont(font)
        # self.Titel.setStyleSheet("color: rgb(255, 255, 255);")
        self.Titel.setAlignment(QtCore.Qt.AlignCenter)
        self.Titel.setObjectName("Titel")
        self.ButtonInsert = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonInsert.setGeometry(QtCore.QRect(850, 640, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonInsert.setFont(font)
        self.ButtonInsert.setObjectName("ButtonInsert")
        self.ButtonUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonUpdate.setGeometry(QtCore.QRect(850, 710, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonUpdate.setFont(font)
        self.ButtonUpdate.setObjectName("ButtonUpdate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 600, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.label.setFont(font)
        # self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 600, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.label_2.setFont(font)
        # self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 600, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.label_3.setFont(font)
        # self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.ButtonInsert.clicked.connect(self.insert)
        self.ButtonUpdate.clicked.connect(self.update)


        self.Table_data.setColumnCount(3)
        # self.Table_data.setRowCount(0)
        # item = QtWidgets.QTableWidgetItem()
        # self.Table_data.setHorizontalHeaderItem(0, item)
        # self.Table_data.setColumnWidth(0, 150)
        # item = QtWidgets.QTableWidgetItem()
        # self.Table_data.setHorizontalHeaderItem(1, item)
        # self.Table_data.setColumnWidth(1, 270)
        # item = QtWidgets.QTableWidgetItem()
        # self.Table_data.setHorizontalHeaderItem(2, item)
        # self.Table_data.setColumnWidth(2, 270)
        self.onChanged()



    def insert(self):
        try:
            connection = connect('Product.db')
            cur = connection.cursor()
            query = f"""INSERT INTO Product VALUES({int(self.textID_insert.text())},{int(self.textName_insert.text())},{int(self.textPrice_insert.text())})"""
            cur.execute(query)
            connection.commit()
            mess = QtWidgets.QMessageBox()
            mess.setIcon(QtWidgets.QMessageBox.Information)
            mess.setWindowIcon(QtGui.QIcon('information.png'))
            mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
            mess.setWindowTitle("Congratulations")
            mess.setText(" Insert Successful ")   
            mess.exec_()
        
        except sqlite3.Error as e :
            text = str(e)
            mess = QtWidgets.QMessageBox()
            mess.setIcon(QtWidgets.QMessageBox.Critical)
            mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
            mess.setWindowIcon(QtGui.QIcon('cancel.png'))
            mess.setWindowTitle("Error")
            mess.setText(text)
            mess.exec_()


    def update(self):

        try:
            connection = connect('Product.db')
            cur = connection.cursor()
            query = """UPDATE Product SET ProductName = {},ProductPrice = {} WHERE ProductID = {}""".format(int(self.textName_update.text()),int(self.textPrice_update.text()),int(self.textId_update.text()))
            cur.execute(query)
            connection.commit()
            mess = QtWidgets.QMessageBox()
            mess.setIcon(QtWidgets.QMessageBox.Information)
            mess.setWindowIcon(QtGui.QIcon('information.png'))
            mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
            mess.setWindowTitle("Congratulations")
            mess.setText(" Insert Successful ")   
            mess.exec_()
        
        except sqlite3.Error as e :
            text = str(e)
            mess = QtWidgets.QMessageBox()
            mess.setIcon(QtWidgets.QMessageBox.Critical)
            mess.setStyleSheet("QLabel{min-height:30 px; font-size: 24px;}")
            mess.setWindowIcon(QtGui.QIcon('cancel.png'))
            mess.setWindowTitle("Error")
            mess.setText(text)
            mess.exec_()


    # Display database 
    def onChanged(self):
        # query = text[0:3]
        connection = sqlite3.connect('Product.db')
        cur = connection.cursor()
        res = cur.execute("SELECT * FROM Product ")

        self.Table_data.horizontalHeader().setStretchLastSection(True)
        self.Table_data.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Stretch)

        for row_number, row_data in enumerate(res):
            self.Table_data.setRowCount(row_number)
            self.Table_data.setColumnCount(len(row_data))
            self.Table_data.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.Table_data.setItem(
                    row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))









    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Background.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/background/background.png\"/></p></body></html>"))
        self.labelInsert.setText(_translate("MainWindow", "INSERT"))
        self.labelUpdate.setText(_translate("MainWindow", "UPDATE"))
        self.Titel.setText(_translate("MainWindow", "FD Exercise"))
        self.ButtonInsert.setText(_translate("MainWindow", "INSERT"))
        self.ButtonUpdate.setText(_translate("MainWindow", "UPDATE"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Price"))
        
        # item = self.Table_data.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "Product ID"))
        # item = self.Table_data.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "Product Name"))
        # item = self.Table_data.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "Product Price"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
